### ISSUE TITLE
Get currently loaded tape

### ISSUE THREAD

**Issue by kornpow** [matmair/brother_ql-inventree#39]
Is there a way with this library to determine what label/tape is currently loaded in the printer? That way I can provide better error messages, and other things related to incompatible tape sizes?

**Comment by matmair** [comment]
I know it is in the comms standard with the printer but the library is not supporting this currently

**Comment by kornpow** [comment]
Cool, good to know it is possible. I'll leave the issue open and maybe someone else or me might take a look someday

**Comment by vulpes2** [comment]
I've implemented some basic media detection in the pull request above, perhaps you would find it useful.

**Comment by kornpow** [comment]
I looked over your PR a bit, looks good! Will try it out on my devices!

**Comment by matmair** [comment]
@kornpow I would be interested in your experience with the PR (best-case as a review/comment on the PR) and which printer/label you are using.

**Comment by matmair** [comment]
This was addressed by @vulpes2 in https://github.com/matmair/brother_ql-inventree/pull/53
