### ISSUE TITLE
Does not cut after printing on PT models

### ISSUE THREAD

**Issue by mkildemaa** [matmair/brother_ql-inventree#54]
Hey.

I am using a PT-P710BT printer but setting the model as PT-P750W in the command.

Label is set as pt12.

Compression flag is set.

It works great in all aspects except that it doesn't cut after printing.

The cut works when setting the model as any of the QL-* models but then it prints only blank labels.

Making this work is extremely important for my project so I'm very grateful for this fork but this small issue is currently an obstacle in fully automating my system.

**Comment by matmair** [comment]
The PT-710BT is not officially supported so this kind of thing can happen. The PT-P710BT is a different form factor - it might be that there are other commands to be sent on this model. As I do not have this model I am not sure I can debug this.

**Comment by mkildemaa** [comment]
> The PT-710BT is not officially supported so this kind of thing can happen. The PT-P710BT is a different form factor - it might be that there are other commands to be sent on this model. As I do not have this model I am not sure I can debug this.

I'm not well versed in Python but I'm trying to make it work myself then by looking what's the difference in the printer cut commands between QL and PT models because when I set the model for example QL-800 then it cuts lilke it should.
