### ISSUE TITLE
Enable Auto-Power On

### ISSUE THREAD

**Issue by kornpow** [matmair/brother_ql-inventree#55]
Auto power-on is the only feature where I am forced to manually update a setting using a GUI on a windows/mac computer. It would be really cool if this library supported toggling this setting! It would make provisioning new printer devices super easy.

https://sine.support/en/articles/8223254-brother-ql-820nwb-badge-printer-enabling-auto-power-on

**Comment by vulpes2** [comment]
These commands are undocumented. I do have some packet captures for those, will look into it when I have time.

**Comment by vulpes2** [comment]
After an hour of tinkering, I have a working implementation now. Will post it after #53 is merged.

**Comment by kornpow** [comment]
Thank you for your help on these tricky problems! It helps the library community greatly!

**Comment by matmair** [comment]
@kornpow please validate if this works for you; I have checked with a QL800 and a few PTs and will close this; Feel free to reopen if it fails for you
