### ISSUE TITLE
Serial/Bluetooth backend

### ISSUE THREAD

**Issue by vulpes2** [matmair/brother_ql-inventree#63]
Some QL and PT printers have Bluetooth, which might be a useful backend to have support for. Bluetooth communication is unfortunately undocumented in any of the command reference manuals, so I have no idea what profile Brother is using for this. The QL-820NWB product spec lists SPP, OPP, BIP and HCRP, it might be possible to use SPP and communicate with the printer like it's a normal serial connection.

**Comment by vulpes2** [comment]
Looked it up and I don't think it's worth the effort to support these. Among the modern PT/QL series, there is only one single device that supports the binary raster protocol on the hardware serial port. Bluetooth tends to be difficult to troubleshoot, and there's no way for us to know if it will just accept the binary raster commands over SPP.

| Model      | Serial     | Bluetooth    |
| ---------- | ---------- | ------------ |
| PT-P710BT  | N/A        | Undocumented |
| PT-P900    | ESC/P only | N/A          |
| PT-P900W   | ESC/P only | N/A          |
| PT-P910BT  | N/A        | SPP          |
| PT-P950NW  | ESC/P only | N/A          |
| QL-720NW   | Yes        | N/A          |
| QL-820NWB  | N/A        | SPP          |
| QL-1110NWB | N/A        | SPP          |

**Comment by matmair** [comment]
This would be an edge use case as Bluetooth is quite a hassle in a production env with a notebook / PC. I think I have seen some python implementation of this protocol somewhere on pypi so nothing I would rank high.

If someone stumbles on this and wants to contribute it: I would be supportive of reviewing an implementation but would need to find a way to access a printer or find a second, independent person to test the new backend.
