### ISSUE TITLE
[PT-series] Is there any other way to print other than image files?

### ISSUE THREAD

**Issue by mkildemaa** [matmair/brother_ql-inventree#66]
I am using this package to mass-print auto-generated HTML templates however the current process of generating an image from HTML has some flaws so I was wondering are there any alternative methods to image files to send print data to the PT-series printers with this package?

Other than that this package has been a lifesafer!

**Comment by matmair** [comment]
Not at the moment, the protocol works with raster images and this has proven to be very reliable.

I have had good results with a pipeline build with Jinja2 templates, WeasyPrint and brother_ql-inventree.
